# LLP Offering

In [1]:
import pandas as pd

In [85]:
comp_data_argos = pd.read_csv(r"C:\Users\gbjaudom\Downloads\year_month_producer_sku_count_with_price_ratings (7).csv", index_col=0)
comp_data_argos.head()

,year_month,producer,price_range,product_name,price_gbp,reviews,rating
0,2019-10,3D Puzzle,0-4.99,5,3.208000,0.800000,4.000000
1,2019-10,3D Puzzle,10-14.99,56,12.555714,1.500000,4.176190
2,2019-10,3D Puzzle,15-20,25,17.479200,2.080000,4.366667
3,2019-10,3D Puzzle,5-9.99,66,7.545455,2.378788,4.325000
4,2019-10,4M,0-4.99,4,4.262500,5.000000,3.300000

In [86]:
prd_count_by_date_df = comp_data_argos.groupby("year_month", as_index="False").agg({"product_name":"sum"}).reset_index()
prd_count_by_date_df

  year_month  product_name
0    2019-10         18980
1    2020-10         22624
2    2021-05          1997

In [45]:
import plotly.graph_objects as go

fig = go.Figure()
fig.add_trace(go.Bar(
    x=prd_count_by_date_df["year_month"],
    y=prd_count_by_date_df["producer"],
    name='WK 1 - 30',
    marker_color='#F9DBBD'
))

fig.update_layout(
    title = "Unique Producers by Date",
    autosize = False,
    width = 1300,
    height = 700,
    template = "plotly_white",
    hovermode='x'
)
fig.update_layout(
    legend=dict(
        x=0.90,
        y=1,
    ))
fig.update_xaxes(showgrid=False)
fig.update_yaxes(showgrid=False)
fig.show()

In [77]:
grouped_comp = comp_data_argos.groupby(["year_month", "price_range"]).agg({"product_name":"sum", "price_gbp":"mean", "reviews":"mean", "rating":"mean",}).reset_index()
grouped_comp

   year_month price_range  product_name  price_gbp      reviews    rating
0     2019-10      0-4.99          1788   3.886307     7.943294  4.091533
1     2019-10    10-14.99          5858  12.667652     9.838662  4.305353
2     2019-10       15-20          5077  17.883934     9.760860  4.286092
3     2019-10      5-9.99          5947   8.092263    12.069043  4.248370
4     2020-10      0-4.99          1590   3.884393    58.691343  4.237990
5     2020-10    10-14.99          7261  12.743217   131.895531  4.410522
6     2020-10       15-20          6346  17.861865   137.745351  4.414213
7     2020-10      5-9.99          6616   8.016613   176.398764  4.340284
8     2021-08      0-4.99            89   3.449438  1201.744231  4.479704
9     2021-08    10-14.99           717  12.522959   728.072158  4.443996
10    2021-08       15-20           724  18.003360   721.040808  4.512922
11    2021-08      5-9.99           603   8.195237  1123.539281  4.472561

## LEGO vs Non-LEGO

In [65]:
comp_df = comp_data_argos[comp_data_argos["producer"] != "LEGO"]
lego_df = pd.read_csv(r"C:\Users\gbjaudom\Downloads\LEGO_year_month_producer_sku_count_with_price_ratings (2).csv", index_col=0)

In [71]:
lego_df

   year_month price_range  product_name  price_gbp
0     2019-10    10-14.99            24  13.035474
1     2019-10       15-20            25  18.367174
2     2019-10      5-9.99            12   8.271333
3     2020-10      0-4.99            10   4.657619
4     2020-10    10-14.99            43  12.671261
5     2020-10       15-20            80  18.386306
6     2020-10      5-9.99            55   8.266250
7     2021-08      0-4.99            15   3.795312
8     2021-08    10-14.99            70  13.319390
9     2021-08       15-20           124  17.966471
10    2021-08      5-9.99           103   8.444372

In [79]:
comp_data_argos[(comp_data_argos["year_month"] == "2021-08") & (comp_data_argos["price_range"] == "0-4.99")]

,year_month,producer,price_range,product_name,price_gbp,reviews,rating
1329,2021-08,Ababuli,0-4.99,1,4.590000,1.000000,4.000000
1350,2021-08,BAKUGAN,0-4.99,1,4.990000,1172.000000,4.400000
1359,2021-08,BTS,0-4.99,4,3.000000,3.250000,5.000000
1395,2021-08,Boxer Gifts,0-4.99,1,3.990000,587.000000,4.100000
1421,2021-08,Cocomelon,0-4.99,1,0.490000,0.000000,NaN
1430,2021-08,Cylme,0-4.99,1,1.700000,4901.000000,4.500000
1431,2021-08,D.A.Y. Republic,0-4.99,1,3.250000,134.000000,4.200000
1449,2021-08,Disney,0-4.99,1,2.990000,589.000000,3.900000
1504,2021-08,Galt,0-4.99,1,4.990000,7.000000,4.900000
1512,2021-08,Graine Créative,0-4.99,1,3.520000,0.000000,NaN
1516,2021-08,Great Gizmos,0-4.99,1,3.490000,8.000000,4.700000
1543,2021-08,Hatchimals,0-4.99,1,4.000000,1.000000,5.000000
1546,2021-08,Henbrandt,0-4.99,1,1.550000,1537.000000,4.000000
1554,2021-08,Hot Wheels,0-4.99,3,4.326667,12849.666667,4.733333
1565,2021-08,ITP,0-4.99,1,2.990000,1221.000000,4.300000
1596,2021-08,Klinkamz,0-4.99,1,2.630000,2872.000000,3.900000
1597,2021-08,Kmart,0-4.99,1,4.990000,1409.000000,4.600000
1599,2021-08,K’NEX,0-4.99,1,4.000000,70.000000,4.700000
1608,2021-08,LEGO,0-4.99,24,3.515417,33.875000,4.436364
1623,2021-08,Lankater,0-4.99,1,4.270000,0.000000,NaN
1653,2021-08,MTS,0-4.99,1,2.590000,1959.000000,4.100000
1665,2021-08,Matchbox,0-4.99,2,3.000000,0.000000,NaN
1707,2021-08,Munchkin,0-4.99,2,4.935000,7915.000000,4.500000
1715,2021-08,Nanoblock,0-4.99,1,1.000000,0.000000,NaN
1719,2021-08,Nayels,0-4.99,1,0.990000,0.000000,NaN
1757,2021-08,Pixar,0-4.99,1,2.000000,14.000000,4.700000
1765,2021-08,Playmobil,0-4.99,10,3.841000,278.900000,4.771429
1771,2021-08,Pokemon,0-4.99,1,3.990000,20.000000,4.600000
1784,2021-08,QASIMOF,0-4.99,3,4.460000,13.333333,4.550000
1791,2021-08,Revell,0-4.99,1,4.920000,939.000000,4.500000
1805,2021-08,Sbarden,0-4.99,1,4.600000,7.000000,4.800000
1806,2021-08,Schleich,0-4.99,1,4.990000,1641.000000,4.900000
1845,2021-08,Super Wings,0-4.99,10,4.000000,0.000000,NaN
1862,2021-08,Tamiya,0-4.99,1,3.890000,140.000000,4.600000
1871,2021-08,Thomas And Friends,0-4.99,1,3.000000,0.000000,NaN
1878,2021-08,Tobar,0-4.99,1,2.990000,2164.000000,3.900000
1900,2021-08,Ultrasonpro,0-4.99,1,2.990000,3965.000000,4.600000
1923,2021-08,Wellnesself,0-4.99,1,2.990000,416.000000,4.500000
1941,2021-08,ZinHen,0-4.99,1,4.080000,0.000000,NaN

In [89]:
data_argos = pd.read_csv(r"C:\Users\gbjaudom\Downloads\with_retailer.csv", index_col=0)

In [95]:
data_argos.groupby(["year_month", "producer", "retailer", "price_range"]).agg({"product_name":"nunique", "price_gbp":"mean", "reviews":"mean", "rating":"mean",}).reset_index().to_csv(r"C:\Users\gbjaudom\OneDrive - LEGO\Documents\python_projects\miscellaneous\data_argos\processed\comp_prod_count.csv")

In [106]:
lg_data_argos = pd.read_csv(r"C:\Users\gbjaudom\Downloads\lego_retailer (1).csv",index_col=0)
lg_data_argos.groupby(["year_month", "retailer", "price_range"]).agg({"product_name":"nunique", "price_gbp":"mean"}).reset_index().to_csv(r"C:\Users\gbjaudom\OneDrive - LEGO\Documents\python_projects\miscellaneous\data_argos\processed\lego_prod_count.csv")

### EDA

In [125]:
df = pd.read_csv(r"C:\Users\gbjaudom\OneDrive - LEGO\Documents\python_projects\miscellaneous\data_argos\processed\comp_prod_count.csv")
df["year_month"] = pd.to_datetime(df["year_month"], dayfirst=True)

In [126]:
comp_df = df[df["producer"] != "LEGO"]
lego_df = df[df["producer"] == "LEGO"]

In [128]:
df.groupby(["year_month", "retailer", "price_range"]).sum().reset_index().sort_values("year_month")

,year_month,retailer,price_range,product_name,price_gbp,reviews,rating
0,2019-10-15,amazon.co.uk,0-4.99,1701,434.959581,848.717083,329.039442
19,2019-10-15,thetoyshop.com,5-9.99,486,270.581675,157.280528,129.521795
18,2019-10-15,thetoyshop.com,15-20,362,773.770032,282.702013,127.857686
17,2019-10-15,thetoyshop.com,10-14.99,517,502.286965,202.251621,141.193715
16,2019-10-15,thetoyshop.com,0-4.99,74,49.875385,25.608654,49.833333
15,2019-10-15,smythstoys.com,5-9.99,26,17.025909,2.181818,4.375000
13,2019-10-15,smythstoys.com,10-14.99,74,26.356925,2.543860,4.744444
12,2019-10-15,smythstoys.com,0-4.99,3,2.993333,0.000000,0.000000
11,2019-10-15,johnlewis.com,5-9.99,118,219.928047,37.253347,51.122549
10,2019-10-15,johnlewis.com,15-20,191,653.005143,82.221429,95.515847
14,2019-10-15,smythstoys.com,15-20,63,37.441731,4.307692,4.871795
8,2019-10-15,johnlewis.com,0-4.99,3,12.970000,3.000000,4.700000
7,2019-10-15,argos.co.uk,5-9.99,48,182.724615,1187.658974,83.771667
6,2019-10-15,argos.co.uk,15-20,352,878.760620,1222.536881,176.127333
5,2019-10-15,argos.co.uk,10-14.99,228,471.865989,3766.129177,171.384306
4,2019-10-15,argos.co.uk,0-4.99,7,10.967500,163.000000,17.375000
3,2019-10-15,amazon.co.uk,5-9.99,5302,1410.652199,2891.579377,635.733673
2,2019-10-15,amazon.co.uk,15-20,4192,3045.763717,1678.641521,620.222067
1,2019-10-15,amazon.co.uk,10-14.99,4942,2285.706604,1707.260705,654.463240
9,2019-10-15,johnlewis.com,10-14.99,185,375.161532,45.241026,60.496207
32,2020-10-15,smythstoys.com,0-4.99,206,166.582010,78.022244,127.545794
33,2020-10-15,smythstoys.com,10-14.99,558,1029.250252,554.660240,311.368283
34,2020-10-15,smythstoys.com,15-20,658,1304.806513,700.648565,286.914911
35,2020-10-15,smythstoys.com,5-9.99,679,583.639233,252.991992,269.654135
39,2020-10-15,thetoyshop.com,5-9.99,633,444.764918,354.302648,220.724603
37,2020-10-15,thetoyshop.com,10-14.99,701,740.911516,423.176809,200.508242
38,2020-10-15,thetoyshop.com,15-20,536,1135.078400,951.084718,205.006536
31,2020-10-15,johnlewis.com,5-9.99,236,287.185173,73.106649,82.065625
36,2020-10-15,thetoyshop.com,0-4.99,103,110.482183,37.678211,58.300000
30,2020-10-15,johnlewis.com,15-20,279,709.477982,58.896853,107.286747
29,2020-10-15,johnlewis.com,10-14.99,225,549.154882,107.691328,108.986036
28,2020-10-15,johnlewis.com,0-4.99,21,17.080278,8.555556,8.533333
21,2020-10-15,amazon.co.uk,10-14.99,5568,2371.445706,38533.554219,793.198172
22,2020-10-15,amazon.co.uk,15-20,4637,3131.413764,33241.261460,732.228899
23,2020-10-15,amazon.co.uk,5-9.99,5155,1506.080259,48775.102220,757.783950
20,2020-10-15,amazon.co.uk,0-4.99,1278,375.372128,7647.117131,344.399495
25,2020-10-15,argos.co.uk,10-14.99,331,761.554496,7875.650427,290.164590
26,2020-10-15,argos.co.uk,15-20,549,1270.950590,3268.484887,294.617007
27,2020-10-15,argos.co.uk,5-9.99,93,282.941268,3762.854762,149.561667
24,2020-10-15,argos.co.uk,0-4.99,3,7.500000,26.000000,4.500000
50,2021-08-15,johnlewis.com,15-20,228,634.348563,187.813211,135.755833
57,2021-08-15,thetoyshop.com,10-14.99,134,447.934931,175.618768,124.266667
56,2021-08-15,thetoyshop.com,0-4.99,28,31.750000,21.650000,24.700000
55,2021-08-15,smythstoys.com,5-9.99,163,59.697325,195.062500,33.175000
54,2021-08-15,smythstoys.com,15-20,170,384.138830,1245.640351,86.647667
53,2021-08-15,smythstoys.com,10-14.99,95,188.403009,503.531008,61.071318
52,2021-08-15,smythstoys.com,0-4.99,23,10.592292,34.125000,9.257143
51,2021-08-15,johnlewis.com,5-9.99,199,177.534136,79.485245,67.284964
49,2021-08-15,johnlewis.com,10-14.99,180,517.959852,195.000733,151.446325
45,2021-08-15,argos.co.uk,10-14.99,142,494.316680,10211.920513,194.900210
47,2021-08-15,argos.co.uk,5-9.99,83,242.664444,4874.950000,127.703571
46,2021-08-15,argos.co.uk,15-20,191,714.487857,3796.504762,171.738459
58,2021-08-15,thetoyshop.com,15-20,144,431.989472,279.257937,89.530159
44,2021-08-15,argos.co.uk,0-4.99,6,8.750000,95.000000,8.900000
43,2021-08-15,amazon.co.uk,5-9.99,230,1007.885494,230532.833333,495.010833
42,2021-08-15,amazon.co.uk,15-20,305,2852.875969,174915.333333,682.550000
41,2021-08-15,amazon.co.uk,10-14.99,282,2059.918786,177628.042856,657.138571
40,2021-08-15,amazon.co.uk,0-4.99,45,106.077222,54036.833333,105.550000
48,2021-08-15,johnlewis.com,0-4.99,12,18.826667,22.166667,13.800000
59,2021-08-15,thetoyshop.com,5-9.99,244,299.529064,142.762053,132.916667

In [129]:
lego_df.groupby(["year_month", "producer", "retailer", "price_range"]).sum().reset_index()

,year_month,producer,retailer,price_range,product_name,price_gbp,reviews,rating
0,2019-10-15,LEGO,amazon.co.uk,0-4.99,366,3.858989,10.038251,4.372851
1,2019-10-15,LEGO,amazon.co.uk,10-14.99,523,26.096324,14.800781,4.382134
2,2019-10-15,LEGO,amazon.co.uk,15-20,450,36.295425,27.666667,4.445745
3,2019-10-15,LEGO,amazon.co.uk,5-9.99,868,16.151698,8.176163,4.450706
4,2019-10-15,LEGO,argos.co.uk,0-4.99,4,2.997500,42.000000,4.775000
5,2019-10-15,LEGO,argos.co.uk,10-14.99,56,25.356625,46.325000,4.838889
6,2019-10-15,LEGO,argos.co.uk,15-20,74,36.051977,21.644068,4.794444
7,2019-10-15,LEGO,argos.co.uk,5-9.99,6,15.600000,68.800000,4.680000
8,2019-10-15,LEGO,johnlewis.com,0-4.99,1,2.990000,3.000000,4.700000
9,2019-10-15,LEGO,johnlewis.com,10-14.99,81,26.368327,7.692308,4.515254
10,2019-10-15,LEGO,johnlewis.com,15-20,88,36.613095,4.871429,4.449180
11,2019-10-15,LEGO,johnlewis.com,5-9.99,55,16.906643,3.956522,4.605882
12,2019-10-15,LEGO,smythstoys.com,0-4.99,3,2.993333,0.000000,0.000000
13,2019-10-15,LEGO,smythstoys.com,10-14.99,74,26.356925,2.543860,4.744444
14,2019-10-15,LEGO,smythstoys.com,15-20,63,37.441731,4.307692,4.871795
15,2019-10-15,LEGO,smythstoys.com,5-9.99,26,17.025909,2.181818,4.375000
16,2019-10-15,LEGO,thetoyshop.com,0-4.99,1,4.000000,8.000000,5.000000
17,2019-10-15,LEGO,thetoyshop.com,10-14.99,67,25.837659,15.040000,4.813953
18,2019-10-15,LEGO,thetoyshop.com,15-20,85,37.614287,13.513514,4.793651
19,2019-10-15,LEGO,thetoyshop.com,5-9.99,55,15.524405,4.979167,4.750000
20,2020-10-15,LEGO,amazon.co.uk,0-4.99,267,8.981515,95.238636,4.580184
21,2020-10-15,LEGO,amazon.co.uk,10-14.99,466,25.524123,163.697101,4.548454
22,2020-10-15,LEGO,amazon.co.uk,15-20,442,36.349695,258.783784,4.572754
23,2020-10-15,LEGO,amazon.co.uk,5-9.99,847,16.198370,91.914545,4.523844
24,2020-10-15,LEGO,argos.co.uk,0-4.99,3,7.500000,26.000000,4.500000
25,2020-10-15,LEGO,argos.co.uk,10-14.99,23,26.037778,86.000000,4.880000
26,2020-10-15,LEGO,argos.co.uk,15-20,62,36.972193,44.636364,4.818182
27,2020-10-15,LEGO,argos.co.uk,5-9.99,30,16.730435,134.571429,4.800000
28,2020-10-15,LEGO,johnlewis.com,0-4.99,17,9.266944,1.555556,4.133333
29,2020-10-15,LEGO,johnlewis.com,10-14.99,74,25.152003,7.739130,4.702941
30,2020-10-15,LEGO,johnlewis.com,15-20,132,36.815356,4.812500,4.588136
31,2020-10-15,LEGO,johnlewis.com,5-9.99,112,16.238134,2.876923,4.809375
32,2020-10-15,LEGO,smythstoys.com,0-4.99,19,9.480000,12.076923,4.540000
33,2020-10-15,LEGO,smythstoys.com,10-14.99,50,26.112014,20.406250,4.556667
34,2020-10-15,LEGO,smythstoys.com,15-20,138,36.816300,15.811765,4.670588
35,2020-10-15,LEGO,smythstoys.com,5-9.99,76,17.270448,6.642857,4.663889
36,2020-10-15,LEGO,thetoyshop.com,0-4.99,4,8.000000,5.500000,4.000000
37,2020-10-15,LEGO,thetoyshop.com,10-14.99,57,24.872348,18.030303,4.892857
38,2020-10-15,LEGO,thetoyshop.com,15-20,110,36.459829,5.892308,4.721311
39,2020-10-15,LEGO,thetoyshop.com,5-9.99,95,15.527273,5.345455,4.755556
40,2021-08-15,LEGO,amazon.co.uk,0-4.99,10,8.342222,477.000000,4.800000
41,2021-08-15,LEGO,amazon.co.uk,10-14.99,30,26.886071,1082.500000,4.750000
42,2021-08-15,LEGO,amazon.co.uk,15-20,68,35.317969,1442.250000,4.775000
43,2021-08-15,LEGO,amazon.co.uk,5-9.99,69,16.098577,1979.500000,4.650000
44,2021-08-15,LEGO,argos.co.uk,0-4.99,5,4.750000,25.000000,4.200000
45,2021-08-15,LEGO,argos.co.uk,10-14.99,22,25.441071,199.125000,4.850000
46,2021-08-15,LEGO,argos.co.uk,15-20,66,35.603175,52.619048,4.876190
47,2021-08-15,LEGO,argos.co.uk,5-9.99,25,16.344444,44.000000,4.628571
48,2021-08-15,LEGO,johnlewis.com,0-4.99,10,8.946667,14.166667,3.900000
49,2021-08-15,LEGO,johnlewis.com,10-14.99,57,26.424479,32.076923,4.730769
50,2021-08-15,LEGO,johnlewis.com,15-20,110,36.286349,22.804878,4.647500
51,2021-08-15,LEGO,johnlewis.com,5-9.99,139,16.779785,11.517857,4.639130
52,2021-08-15,LEGO,smythstoys.com,0-4.99,22,6.602292,14.125000,4.657143
53,2021-08-15,LEGO,smythstoys.com,10-14.99,75,26.593009,30.697674,4.704651
54,2021-08-15,LEGO,smythstoys.com,15-20,139,36.485497,29.223684,4.789333
55,2021-08-15,LEGO,smythstoys.com,5-9.99,155,15.462325,14.562500,4.675000
56,2021-08-15,LEGO,thetoyshop.com,0-4.99,2,3.750000,0.000000,0.000000
57,2021-08-15,LEGO,thetoyshop.com,10-14.99,21,23.804545,14.500000,4.733333
58,2021-08-15,LEGO,thetoyshop.com,15-20,76,35.367647,3.250000,4.585714
59,2021-08-15,LEGO,thetoyshop.com,5-9.99,93,17.017123,4.150000,4.620000

In [133]:
all_df = df.groupby(["year_month", "retailer", "price_range"]).sum().reset_index()
lego_df2 = lego_df.groupby(["year_month", "producer", "retailer", "price_range"]).sum().reset_index()

free_df = pd.data_argosFrame()
free_df["date"] = lego_df2["year_month"]
free_df["retailer"] = lego_df2["retailer"]
free_df["price_range"] = lego_df2["price_range"]
free_df["lego_share"] = lego_df2["product_name"] / all_df["product_name"]
free_df.to_csv(r"C:\Users\gbjaudom\OneDrive - LEGO\Documents\python_projects\miscellaneous\data_argos\processed\rating_share.csv")

,year_month,producer,retailer,price_range,product_name,price_gbp,reviews,rating
0,15/08/2021,LEGO,amazon.co.uk,0-4.99,10,8.342222,477.000000,4.800000
1,15/08/2021,LEGO,amazon.co.uk,10-14.99,30,26.886071,1082.500000,4.750000
2,15/08/2021,LEGO,amazon.co.uk,15-20,68,35.317969,1442.250000,4.775000
3,15/08/2021,LEGO,amazon.co.uk,5-9.99,69,16.098577,1979.500000,4.650000
4,15/08/2021,LEGO,argos.co.uk,0-4.99,5,4.750000,25.000000,4.200000
5,15/08/2021,LEGO,argos.co.uk,10-14.99,22,25.441071,199.125000,4.850000
6,15/08/2021,LEGO,argos.co.uk,15-20,66,35.603175,52.619048,4.876190
7,15/08/2021,LEGO,argos.co.uk,5-9.99,25,16.344444,44.000000,4.628571
8,15/08/2021,LEGO,johnlewis.com,0-4.99,10,8.946667,14.166667,3.900000
9,15/08/2021,LEGO,johnlewis.com,10-14.99,57,26.424479,32.076923,4.730769
10,15/08/2021,LEGO,johnlewis.com,15-20,110,36.286349,22.804878,4.647500
11,15/08/2021,LEGO,johnlewis.com,5-9.99,139,16.779785,11.517857,4.639130
12,15/08/2021,LEGO,smythstoys.com,0-4.99,22,6.602292,14.125000,4.657143
13,15/08/2021,LEGO,smythstoys.com,10-14.99,75,26.593009,30.697674,4.704651
14,15/08/2021,LEGO,smythstoys.com,15-20,139,36.485497,29.223684,4.789333
15,15/08/2021,LEGO,smythstoys.com,5-9.99,155,15.462325,14.562500,4.675000
16,15/08/2021,LEGO,thetoyshop.com,0-4.99,2,3.750000,0.000000,0.000000
17,15/08/2021,LEGO,thetoyshop.com,10-14.99,21,23.804545,14.500000,4.733333
18,15/08/2021,LEGO,thetoyshop.com,15-20,76,35.367647,3.250000,4.585714
19,15/08/2021,LEGO,thetoyshop.com,5-9.99,93,17.017123,4.150000,4.620000
20,15/10/2019,LEGO,amazon.co.uk,0-4.99,366,3.858989,10.038251,4.372851
21,15/10/2019,LEGO,amazon.co.uk,10-14.99,523,26.096324,14.800781,4.382134
22,15/10/2019,LEGO,amazon.co.uk,15-20,450,36.295425,27.666667,4.445745
23,15/10/2019,LEGO,amazon.co.uk,5-9.99,868,16.151698,8.176163,4.450706
24,15/10/2019,LEGO,argos.co.uk,0-4.99,4,2.997500,42.000000,4.775000
25,15/10/2019,LEGO,argos.co.uk,10-14.99,56,25.356625,46.325000,4.838889
26,15/10/2019,LEGO,argos.co.uk,15-20,74,36.051977,21.644068,4.794444
27,15/10/2019,LEGO,argos.co.uk,5-9.99,6,15.600000,68.800000,4.680000
28,15/10/2019,LEGO,johnlewis.com,0-4.99,1,2.990000,3.000000,4.700000
29,15/10/2019,LEGO,johnlewis.com,10-14.99,81,26.368327,7.692308,4.515254
30,15/10/2019,LEGO,johnlewis.com,15-20,88,36.613095,4.871429,4.449180
31,15/10/2019,LEGO,johnlewis.com,5-9.99,55,16.906643,3.956522,4.605882
32,15/10/2019,LEGO,smythstoys.com,0-4.99,3,2.993333,0.000000,0.000000
33,15/10/2019,LEGO,smythstoys.com,10-14.99,74,26.356925,2.543860,4.744444
34,15/10/2019,LEGO,smythstoys.com,15-20,63,37.441731,4.307692,4.871795
35,15/10/2019,LEGO,smythstoys.com,5-9.99,26,17.025909,2.181818,4.375000
36,15/10/2019,LEGO,thetoyshop.com,0-4.99,1,4.000000,8.000000,5.000000
37,15/10/2019,LEGO,thetoyshop.com,10-14.99,67,25.837659,15.040000,4.813953
38,15/10/2019,LEGO,thetoyshop.com,15-20,85,37.614287,13.513514,4.793651
39,15/10/2019,LEGO,thetoyshop.com,5-9.99,55,15.524405,4.979167,4.750000
40,15/10/2020,LEGO,amazon.co.uk,0-4.99,267,8.981515,95.238636,4.580184
41,15/10/2020,LEGO,amazon.co.uk,10-14.99,466,25.524123,163.697101,4.548454
42,15/10/2020,LEGO,amazon.co.uk,15-20,442,36.349695,258.783784,4.572754
43,15/10/2020,LEGO,amazon.co.uk,5-9.99,847,16.198370,91.914545,4.523844
44,15/10/2020,LEGO,argos.co.uk,0-4.99,3,7.500000,26.000000,4.500000
45,15/10/2020,LEGO,argos.co.uk,10-14.99,23,26.037778,86.000000,4.880000
46,15/10/2020,LEGO,argos.co.uk,15-20,62,36.972193,44.636364,4.818182
47,15/10/2020,LEGO,argos.co.uk,5-9.99,30,16.730435,134.571429,4.800000
48,15/10/2020,LEGO,johnlewis.com,0-4.99,17,9.266944,1.555556,4.133333
49,15/10/2020,LEGO,johnlewis.com,10-14.99,74,25.152003,7.739130,4.702941
50,15/10/2020,LEGO,johnlewis.com,15-20,132,36.815356,4.812500,4.588136
51,15/10/2020,LEGO,johnlewis.com,5-9.99,112,16.238134,2.876923,4.809375
52,15/10/2020,LEGO,smythstoys.com,0-4.99,19,9.480000,12.076923,4.540000
53,15/10/2020,LEGO,smythstoys.com,10-14.99,50,26.112014,20.406250,4.556667
54,15/10/2020,LEGO,smythstoys.com,15-20,138,36.816300,15.811765,4.670588
55,15/10/2020,LEGO,smythstoys.com,5-9.99,76,17.270448,6.642857,4.663889
56,15/10/2020,LEGO,thetoyshop.com,0-4.99,4,8.000000,5.500000,4.000000
57,15/10/2020,LEGO,thetoyshop.com,10-14.99,57,24.872348,18.030303,4.892857
58,15/10/2020,LEGO,thetoyshop.com,15-20,110,36.459829,5.892308,4.721311
59,15/10/2020,LEGO,thetoyshop.com,5-9.99,95,15.527273,5.345455,4.755556

# Single Retailer

In [134]:
comp_df = pd.read_csv(r"C:\Users\gbjaudom\Downloads\comp_argos_monthly.csv", index_col=0)
lego_df = pd.read_csv(r"C:\Users\gbjaudom\Downloads\lego_argos_monthly.csv", index_col=0)

In [156]:
# Current comp
lego_df.tail(10)

    year_month price_range  price_gbp  product_name
119    2021-09       15-20  18.136951            94
120    2021-09      5-9.99   8.198576            78
121    2021-10      0-4.99   4.675714             7
122    2021-10    10-14.99  13.141264            49
123    2021-10       15-20  18.220611            95
124    2021-10      5-9.99   8.149367            75
125    2021-11      0-4.99   4.214444             9
126    2021-11    10-14.99  12.953795            46
127    2021-11       15-20  18.172463            90
128    2021-11      5-9.99   8.210045            82

In [175]:
m = comp_df.groupby(["year_month", "price_range"]).sum().reset_index()
m[m["year_month"] == "2021-05"]

   year_month price_range  product_name    price_gbp       reviews      rating
68    2021-05      0-4.99          1125   447.790842  38721.020985  426.904452
69    2021-05    10-14.99          5989  2430.227786  39168.224915  798.746929
70    2021-05       15-20          5423  3091.054655  31210.029780  749.726444
71    2021-05      5-9.99          6204  1597.574541  68885.824556  804.189198

In [166]:
all_df = pd.read_csv(r"C:\Users\gbjaudom\LEGO\WE eComm CoE Analytics Team - Documents\Insights Projects\11_21 LPP Offering\argos_producer_by_month_price.csv")
all_df = all_df.groupby(["year_month", "price_range"]).sum().reset_index()

In [178]:

b = lego_df[(lego_df["year_month"] >= "2019-10") & (lego_df["year_month"] <= "2021-09")]
b["l_pr"] = b["price_range"]
b["l_product_name"] = b["product_name"]
final = all_df.merge(b, on=["year_month", "price_range"], how="left")

ipykernel_launcher:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

ipykernel_launcher:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [179]:
final.columns

Index(['year_month', 'price_range', 'product_name_x', 'price_gbp_x', 'reviews',
       'rating', 'price_gbp_y', 'product_name_y', 'l_pr', 'l_product_name'],
      dtype='object')

In [183]:
data_argos = final[['year_month', 'price_range', 'product_name_x', 'product_name_y']]
data_argos["lego_share"] = data_argos['product_name_y'] / data_argos['product_name_x']
data_argos

ipykernel_launcher:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

   year_month price_range  product_name_x  product_name_y  lego_share
0     2019-10      0-4.99            2365             NaN         NaN
1     2019-10    10-14.99            7570            25.0    0.003303
2     2019-10       15-20            6775            21.0    0.003100
3     2019-10      5-9.99            7276            13.0    0.001787
4     2019-11      0-4.99            3294             NaN         NaN
..        ...         ...             ...             ...         ...
91    2021-08      5-9.99             538            89.0    0.165428
92    2021-09      0-4.99              30            11.0    0.366667
93    2021-09    10-14.99             234            63.0    0.269231
94    2021-09       15-20             278            94.0    0.338129
95    2021-09      5-9.99             177            78.0    0.440678

[96 rows x 5 columns]

In [193]:
list(data_argos[data_argos["price_range"] == "5-9.99"]["lego_share"])

[0.0017866959868059373,
 0.0015539210608101108,
 0.0016432953549517966,
 0.0034626865671641793,
 0.003915810083210965,
 0.003432620972206843,
 0.0024127877752086056,
 0.0034620794114465,
 0.004315460135936994,
 0.003493270317476626,
 0.004142931123770067,
 0.004606408025386427,
 0.0031077694235588974,
 0.0034729112919230005,
 0.005965532479010163,
 0.0109868550127526,
 1.0,
 1.0,
 0.011534674356449571,
 0.013358778625954198,
 0.11794228356336262,
 0.13848396501457727,
 0.1654275092936803,
 0.4406779661016949]

In [196]:
argos = pd.data_argosFrame()

argos["z_5"] = list(data_argos[data_argos["price_range"] == "0-4.99"]["lego_share"])
argos["f_10"] = list(data_argos[data_argos["price_range"] == "5-9.99"]["lego_share"])
argos["t_15"] = list(data_argos[data_argos["price_range"] == "10-14.99"]["lego_share"])
argos["f_20"] = list(data_argos[data_argos["price_range"] == "15-20"]["lego_share"])
argos["time"] = data_argos["year_month"].unique()

argos.to_csv(r"C:\Users\gbjaudom\LEGO\WE eComm CoE Analytics Team - Documents\Insights Projects\11_21 LPP Offering\lego_share_by_month.csv")

## Argos

In [207]:
agros = pd.read_csv(r"C:\Users\gbjaudom\LEGO\WE eComm CoE Analytics Team - Documents\Insights Projects\11_21 LPP Offering\argos_producer_by_month.csv")
argos_all = agros.groupby(["year_month", "price_range"]).sum().reset_index()
len(argos_all)

96

In [209]:
argos_lego = pd.read_csv(r"C:\Users\gbjaudom\Downloads\lego_argos_monthly.csv", index_col=0)
argos_lego.head()

  year_month price_range  price_gbp  product_name
0    2019-01    10-14.99  13.291000            10
1    2019-01       15-20  18.657778             9
2    2019-01      5-9.99   8.490000             2
3    2019-02    10-14.99  13.291000            10
4    2019-02       15-20  18.277143             7

In [213]:
argos_merged = argos_all.merge(argos_lego, on=["year_month", "price_range"], how="left")
data_argos_argos = argos_merged[['year_month', 'price_range', 'product_name_x', 'product_name_y']]
data_argos_argos["lego_share"] = data_argos_argos['product_name_y'] / data_argos_argos['product_name_x']
data_argos_argos.head()

ipykernel_launcher:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  year_month price_range  product_name_x  product_name_y  lego_share
0    2019-10      0-4.99               4             1.0    0.250000
1    2019-10    10-14.99             268            22.0    0.082090
2    2019-10       15-20             377            22.0    0.058355
3    2019-10      5-9.99              72             7.0    0.097222
4    2019-11      0-4.99               4             NaN         NaN

In [219]:
argos = pd.DataFrame()
argos["z_5"] = list(data_argos[data_argos["price_range"] == "0-4.99"]["lego_share"])
argos["f_10"] = list(data_argos[data_argos["price_range"] == "5-9.99"]["lego_share"])
argos["t_15"] = list(data_argos[data_argos["price_range"] == "10-14.99"]["lego_share"])
argos["f_20"] = list(data_argos[data_argos["price_range"] == "15-20"]["lego_share"])
argos["time"] = data_argos["year_month"].unique()
argos.to_csv(r"C:\Users\gbjaudom\LEGO\WE eComm CoE Analytics Team - Documents\Insights Projects\11_21 LPP Offering\argos_lego_share_by_month.csv")

## ToyShop

In [222]:
toy = pd.read_csv(r"C:\Users\gbjaudom\LEGO\WE eComm CoE Analytics Team - Documents\Insights Projects\11_21 LPP Offering\toyshop_producer_by_month.csv")
toy_all = toy.groupby(["year_month", "price_range"]).sum().reset_index()
len(toy_all)

96

In [224]:
ts_lego = pd.read_csv(r"C:\Users\gbjaudom\Downloads\lego_{}_monthly.csv", index_col=0)
ts_lego.head()

  year_month price_range  price_gbp  product_name
0    2019-01    10-14.99  12.022000            15
1    2019-01       15-20  17.545455            11
2    2019-01      5-9.99   7.750000             4
3    2019-02    10-14.99  12.145625            16
4    2019-02       15-20  17.750000            12

In [226]:
ts_merged = toy_all.merge(ts_lego, on=["year_month", "price_range"], how="left")
data_ts = ts_merged[['year_month', 'price_range', 'product_name_x', 'product_name_y']]
data_ts["lego_share"] = data_ts['product_name_y'] / data_ts['product_name_x']
print(len(data_ts))
data_ts.head()

96

ipykernel_launcher:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  year_month price_range  product_name_x  product_name_y  lego_share
0    2019-10      0-4.99              86             NaN         NaN
1    2019-10    10-14.99             550            20.0    0.036364
2    2019-10       15-20             316            19.0    0.060127
3    2019-10      5-9.99             518             7.0    0.013514
4    2019-11      0-4.99              66             NaN         NaN

In [227]:
argos = pd.DataFrame()
argos["z_5"] = list(data_ts[data_ts["price_range"] == "0-4.99"]["lego_share"])
argos["f_10"] = list(data_ts[data_ts["price_range"] == "5-9.99"]["lego_share"])
argos["t_15"] = list(data_ts[data_ts["price_range"] == "10-14.99"]["lego_share"])
argos["f_20"] = list(data_ts[data_ts["price_range"] == "15-20"]["lego_share"])
argos["time"] = data_ts["year_month"].unique()
argos.to_csv(r"C:\Users\gbjaudom\LEGO\WE eComm CoE Analytics Team - Documents\Insights Projects\11_21 LPP Offering\toyshop_lego_share_by_month.csv")

### Symths

In [228]:
smyth = pd.read_csv(r"C:\Users\gbjaudom\LEGO\WE eComm CoE Analytics Team - Documents\Insights Projects\11_21 LPP Offering\smythtoys_lego_share_by_month.csv")
smyth_all = smyth.groupby(["year_month", "price_range"]).sum().reset_index()
len(smyth_all)

76

In [230]:
sy_lego = pd.read_csv(r"C:\Users\gbjaudom\Downloads\lego_smythstoys_monthly.csv", index_col=0)
sy_lego.head()

  year_month price_range  price_gbp  product_name
0    2019-01    10-14.99  13.478506             9
1    2019-01       15-20  18.572759            10
2    2019-01      5-9.99   8.990000             9
3    2019-02    10-14.99  13.497143            10
4    2019-02       15-20  18.650714            12

In [231]:
sy_merged = smyth_all.merge(sy_lego, on=["year_month", "price_range"], how="left")
data_sy = sy_merged[['year_month', 'price_range', 'product_name_x', 'product_name_y']]
data_sy["lego_share"] = data_sy['product_name_y'] / data_sy['product_name_x']
print(len(data_sy))
data_sy.head()

76

ipykernel_launcher:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  year_month price_range  product_name_x  product_name_y  lego_share
0    2020-03      0-4.99             226               4    0.017699
1    2020-03    10-14.99             491              25    0.050916
2    2020-03       15-20             503              47    0.093439
3    2020-03      5-9.99             709              23    0.032440
4    2020-04      0-4.99             206               4    0.019417

In [232]:
argos = pd.DataFrame()
argos["z_5"] = list(data_sy[data_sy["price_range"] == "0-4.99"]["lego_share"])
argos["f_10"] = list(data_sy[data_sy["price_range"] == "5-9.99"]["lego_share"])
argos["t_15"] = list(data_sy[data_sy["price_range"] == "10-14.99"]["lego_share"])
argos["f_20"] = list(data_sy[data_sy["price_range"] == "15-20"]["lego_share"])
argos["time"] = data_sy["year_month"].unique()
argos.to_csv(r"C:\Users\gbjaudom\LEGO\WE eComm CoE Analytics Team - Documents\Insights Projects\11_21 LPP Offering\symthstoys_lego_share_by_month.csv")

### ASDA

In [248]:
asda = pd.read_csv(r"C:\Users\gbjaudom\LEGO\WE eComm CoE Analytics Team - Documents\Insights Projects\11_21 LPP Offering\asda_producer_by_month.csv")
smyth_all = asda.groupby(["year_month", "price_range"]).sum().reset_index()
len(smyth_all)

82

In [249]:
sy_lego = pd.read_csv(r"C:\Users\gbjaudom\Downloads\lego_direct_monthly.csv", index_col=0)
sy_lego.head()

  year_month price_range  price_gbp  product_name
0    2019-01    10-14.99  13.724386             6
1    2019-01       15-20  17.720000             8
2    2019-01      5-9.99   9.970000             2
3    2019-02    10-14.99  13.414433             8
4    2019-02       15-20  17.970000             7

In [250]:
sy_merged = smyth_all.merge(sy_lego, on=["year_month", "price_range"], how="left")
data_sy = sy_merged[['year_month', 'price_range', 'product_name_x', 'product_name_y']]
data_sy["lego_share"] = data_sy['product_name_y'] / data_sy['product_name_x']
print(len(data_sy))
data_sy.head()

82

  year_month price_range  product_name_x  product_name_y  lego_share
0    2019-10      0-4.99               1             NaN         NaN
1    2019-10    10-14.99             104            12.0    0.115385
2    2019-10       15-20             120            12.0    0.100000
3    2019-10      5-9.99              43             4.0    0.093023
4    2019-11      0-4.99               3             NaN         NaN

In [251]:
list(data_sy[data_sy["price_range"] == "0-4.99"]["lego_share"])

[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]

In [252]:
argos = pd.DataFrame()
# argos["z_5"] = list(data_sy[data_sy["price_range"] == "0-4.99"]["lego_share"])
argos["f_10"] = list(data_sy[data_sy["price_range"] == "5-9.99"]["lego_share"])
argos["t_15"] = list(data_sy[data_sy["price_range"] == "10-14.99"]["lego_share"])
argos["f_20"] = list(data_sy[data_sy["price_range"] == "15-20"]["lego_share"])
argos["time"] = data_sy["year_month"].unique()
argos.to_csv(r"C:\Users\gbjaudom\LEGO\WE eComm CoE Analytics Team - Documents\Insights Projects\11_21 LPP Offering\asda_lego_share_by_month.csv")

### John Lewis

In [253]:
asda = pd.read_csv(r"C:\Users\gbjaudom\LEGO\WE eComm CoE Analytics Team - Documents\Insights Projects\11_21 LPP Offering\johnlewis_producer_by_month.csv")
smyth_all = asda.groupby(["year_month", "price_range"]).sum().reset_index()
len(smyth_all)

96

In [254]:
sy_lego = pd.read_csv(r"C:\Users\gbjaudom\Downloads\lego_johnlewis_monthly.csv", index_col=0)
sy_lego.head()

  year_month price_range  price_gbp  product_name
0    2019-01      0-4.99   4.990000             1
1    2019-01    10-14.99  13.394251            13
2    2019-01       15-20  18.274499            14
3    2019-01      5-9.99   9.055290            10
4    2019-02    10-14.99  13.278516            13

In [255]:
sy_merged = smyth_all.merge(sy_lego, on=["year_month", "price_range"], how="left")
data_sy = sy_merged[['year_month', 'price_range', 'product_name_x', 'product_name_y']]
data_sy["lego_share"] = data_sy['product_name_y'] / data_sy['product_name_x']
print(len(data_sy))
data_sy.head()

96

  year_month price_range  product_name_x  product_name_y  lego_share
0    2019-10      0-4.99               6             NaN         NaN
1    2019-10    10-14.99             151            20.0    0.132450
2    2019-10       15-20             162            23.0    0.141975
3    2019-10      5-9.99             104            15.0    0.144231
4    2019-11      0-4.99               6             NaN         NaN

In [256]:
argos = pd.DataFrame()
argos["z_5"] = list(data_sy[data_sy["price_range"] == "0-4.99"]["lego_share"])
argos["f_10"] = list(data_sy[data_sy["price_range"] == "5-9.99"]["lego_share"])
argos["t_15"] = list(data_sy[data_sy["price_range"] == "10-14.99"]["lego_share"])
argos["f_20"] = list(data_sy[data_sy["price_range"] == "15-20"]["lego_share"])
argos["time"] = data_sy["year_month"].unique()
argos.to_csv(r"C:\Users\gbjaudom\LEGO\WE eComm CoE Analytics Team - Documents\Insights Projects\11_21 LPP Offering\johnlewis_lego_share_by_month.csv")